### PR TITLE
Remove un-necessary function name. Fixes #80

### LINKED ISSUE #80: Very strange async problem
I'm getting a strange problem when the first use of chalk is in an async callback thread.
Node 0.12.6

```
[ReferenceError: builder is not defined]
ReferenceError: builder is not defined
    at Chalk.builder (c:\git\node-markdown-spellcheck\node_modules\chalk\index.js:40:27)
    at c:\git\node-markdown-spellcheck\es5\cli.js:221:58
    at c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:187:20
    at iterate (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:265:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:284:9)
    at Object.async.forEachSeries.async.eachSeries (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:220:22)
    at c:\git\node-markdown-spellcheck\es5\cli.js:219:26
    at c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:697:13
    at c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:52:16
    at done (c:\git\node-markdown-spellcheck\node_modules\async\lib\async.js:248:21)
```

I've looked at the code

```
	var builder = function builder() {
		return applyStyle.apply(builder, arguments);
	};
```

and I've no idea why it is going wrong - the function expression name should be exposed.

If I change the chalk code in my node_modules to...

```
	var builder = function () {
		return applyStyle.apply(builder, arguments);
	};
```

then it works.

If I add a dummy call to chalk before I start doing async things, it works

```
chalk.red("red"); // fix very weird bug
```

The only explanation I have is that its a weird V8 bug. I'm raising here in case there is something I missed, or you have seen it before or you had been thinking about removing the function name anyway.

### PR DESCRIPTION
**Pull request by lukeapage**
See discussion on #80

### CODE REVIEW

**Comment by Qix-** [comment]
I can't approve this until I have a reproducible piece of code that will show the error. As @alexbeletsky [mentioned](https://github.com/chalk/chalk/issues/80#issuecomment-132633979), it's node 0.12.5 on Mac, though I tried a few pieces of code and can't reproduce.

The commit looks okay, but I don't see how it would change anything. If it's a bug in V8 (or Node proper) then it should be filed there (we can still apply a fix, but I want to be sure).

Can you please write something that can reproduce this?

**Comment by alexbeletsky** [comment]
+1 to merge that and republish the package. It fails for node > 0.12.5 and many projects depends on `chalk` including `grunt-uglify` that brakes the build of my project currently.

**Comment by Qix-** [comment]
Just need some reproducible code :dancer:

**Comment by lukeapage** [comment]
i can put together instructions to reproduce, though it may well be timing
dependent.  stable v8 bugs are often difficult to reproduce outside the
environment they occur in.. ive seen some crazy stuff impossible to create
a test case for.

**Comment by Qix-** [comment]
If that's the case then that indicates it's less of a chalk bug.

// @sindresorhus to aisle 3, please :)

**Comment by alexbeletsky** [comment]
I've created a simple project, replica of big project I currently working on, to put it on github.. I can't reproduce it there, yet.. It's a floating bug :-|

**Comment by Qix-** [comment]
Those are the worst. My reservation is merging something that doesn't seem necessary for a bug that can't be reproduced and isn't specifically chalk's fault. That's a call that @sindresorhus will need to make, unfortunately. I don't see how it'd change much of anything but it's more of a stylistic thing.

For starters, do both @alexbeletsky and @lukeapage concur the fix in the PR works? He'll want to know.

**Comment by alexbeletsky** [comment]
I confirm the problem.. first I thought it's the `time-grunt` issue, but further diagnosis went to `chalk` library. Here is the output of `grunt` run, that shows the issue:

```
 grunt build:prod --debug --stack
Running "clean:build" (clean) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-clean/tasks/clean.js
>> 1 path cleaned.

Running "browserify:prod" (browserify) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-browserify/tasks/browserify.js
>> Bundle source/build/app.js created.

Running "compass:dev" (compass) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-compass/tasks/compass.js

Running "uglify:main" (uglify) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js
Warning: builder is not defined Use --force to continue.
ReferenceError: builder is not defined
    at Chalk.builder (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/node_modules/chalk/index.js:40:27)
    at /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js:176:45
    at Array.forEach (native)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js:63:16)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:227:11

Aborted due to warnings.
```

If I go and manually change `node_modules/grunt-contib-uglify/node_modules/chalk` as @lukeapage PR, all is good! It fails after in `cssmin` task, cause it also depends on `chalk` and have it's own copy of the module.

```
 grunt build:prod --debug --stack
Running "clean:build" (clean) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-clean/tasks/clean.js
>> 1 path cleaned.

Running "browserify:prod" (browserify) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-browserify/tasks/browserify.js
>> Bundle source/build/app.js created.

Running "compass:dev" (compass) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-compass/tasks/compass.js

Running "uglify:main" (uglify) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-uglify/tasks/uglify.js
>> 1 file created.

Running "cssmin:minify" (cssmin) task
[D] Task source: /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-cssmin/tasks/cssmin.js
Warning: builder is not defined Use --force to continue.
ReferenceError: builder is not defined
    at Chalk.builder (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-cssmin/node_modules/chalk/index.js:40:27)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-cssmin/tasks/cssmin.js:81:45)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt-contrib-cssmin/tasks/cssmin.js:30:16)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:300:12)
    at /Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/lib/util/task.js:227:11
```

I clearly understand, it seems like a strange change.. and it's hard to create any meaningful tests, but it solves the issue.

**Comment by lukeapage** [comment]
I've tried to make a stand-alone test case and failed.

reproduction steps for me:
```
git clone git@github.com:lukeapage/node-markdown-spellcheck.git
npm i
vi es5/cli.js
# comment out this line -   _chalk2['default'].red("red"); // fix very weird bug - https://github.com/chalk/chalk/issues/80 
# and save
node bin/mdspell "*.md"
```

**Comment by lukeapage** [comment]
> Those are the worst. My reservation is merging something that doesn't seem necessary for a bug that can't be reproduced 

by you.. 

> and isn't specifically chalk's fault. 

Its definitely valid JavaScript code, so it isn't an error in chalk, however it is a little bit weird.. you are using 2 different bindings to the same thing unnecessarily.

> As well, has a bug been filed over at joyent/node?

No, but no matter what, 0.12 is out and I highly doubt an upgrade of V8 will occur for this little bug. I think I would have to spend alot more time creating test-cases.

My view is that the upsides of working around a v8 bug in nodejs outweigh the downsides of having a seemingly unnecessary change made to the source.

I've just spent another 20 minutes trying to make a simplified test case - opening a file 1000 times, then calling chalk.

**Comment by Qix-** [comment]
> by you..

If it can't be reproduced then I can't validate that this PR is going to fix it ;) That's why I'm calling in @sindresorhus. It's his decision whether or not to blindly accept it.

> however it is a little bit weird.. you are using 2 different bindings to the same thing unnecessarily.

Not quite sure I follow; the function name is there so things like `builder.name` work and debugging is easier (as stack traces won't show names for anonymous functions).

**Comment by lukeapage** [comment]
> Not quite sure I follow; the function name is there so things like builder.name work and debugging is easier (as stack traces won't show names for anonymous functions).

In Node.js They do show line numbers and filenames though, so that is rarely an issue. There are other anonymous functions in the file.

However.. It may be a fix to remove the `var builder =` instead of the function name if you are concerned.

Did you try my reproduction steps above?

**Comment by Qix-** [comment]
@lukeapage thanks, that does reproduce. Interesting, let me take a look.

**Comment by Qix-** [comment]
Also, the following just results in a color-less successful run of the program. No errors.

```javascript
function build(_styles) {
	var builder = function builder() {
		return applyStyle.apply(this, arguments);
	};
  builder = builder.bind(builder);

	builder._styles = _styles;
	builder.enabled = this.enabled;
	// __proto__ is used because we must return a function, but there is
	// no way to create a function with a different prototype.
	/*eslint no-proto: 0 */
	builder.__proto__ = proto;

	return builder;
}
```

**Comment by Qix-** [comment]
Can also confirm using the literal term `builder` is not a problem:

```javascript
function build(_styles) {
	var unicorn = function unicorn() {
		return applyStyle.apply(unicorn, arguments);
	};

	unicorn._styles = _styles;
	unicorn.enabled = this.enabled;
	// __proto__ is used because we must return a function, but there is
	// no way to create a function with a different prototype.
	/*eslint no-proto: 0 */
	unicorn.__proto__ = proto;

	return unicorn;
}
```

yields

```
/private/tmp/chalk-repro/node_modules/chalk/index.js:40
		return applyStyle.apply(unicorn, arguments);
		                        ^
ReferenceError: unicorn is not defined
    at Chalk.unicorn (/private/tmp/chalk-repro/node_modules/chalk/index.js:40:27)
    at /private/tmp/chalk-repro/es5/cli.js:69:54
    at /private/tmp/chalk-repro/es5/multi-file-processor.js:47:7
    at /private/tmp/chalk-repro/node_modules/async/lib/async.js:358:13
    at iterate (/private/tmp/chalk-repro/node_modules/async/lib/async.js:265:13)
    at async.forEachOfSeries.async.eachOfSeries (/private/tmp/chalk-repro/node_modules/async/lib/async.js:284:9)
    at _asyncMap (/private/tmp/chalk-repro/node_modules/async/lib/async.js:357:9)
    at Object.mapSeries (/private/tmp/chalk-repro/node_modules/async/lib/async.js:350:20)
    at /private/tmp/chalk-repro/es5/multi-file-processor.js:41:24
    at /private/tmp/chalk-repro/node_modules/async/lib/async.js:697:13
```

**Comment by sindresorhus** [comment]
Lol. Weirdest bug I've seen in a long time.

I'm fine with removing the name as it's moot. According to the ES2015 spec engines should be able to infer the name from the variable.

Do feel free to continue discussing this though.

**Comment by sindresorhus** [comment]
1.1.1 is out: https://github.com/chalk/chalk/releases/tag/v1.1.1

**Comment by alexbeletsky** [comment]
I confirm the fix in `1.1.1`. 

There is still issue in https://github.com/gruntjs/grunt-contrib-copy/issues/251, that still blocks my build, hope that package is re-published with updated depencies.

@lukeapage @Qix- @lukeapage thanks a lot for reacting on that that quickly, it's really blocking me.. fortunatelly it's progressing.

**Pull request merged**
