### PR TITLE
ansi-styles and support-color correction

### PR DESCRIPTION
**Pull request by phricardorj**
Cannot find module '#ansi-styles' from 'node_modules/chalk/source/index.js'
 Cannot find module '#supports-color' from 'node_modules/chalk/source/index.js'

I was doing unit tests with Chalk 5 using Jest and we got these two errors. I made some changes to make it work, I'm using "ansi-styles" in version "^6.1.0" and "support-color" in version "^9.2.2". After securing the latest version, remove the "#" in the import of the two in "source/index.js". At Jest, I work with ECMAScript Modules in their experimental support. This change solved the problem, being the reason for me opening this "pull request", I don't know if it's the best way to solve these errors. But, that's what worked in my application!

### CODE REVIEW

**Comment by Qix-** [comment]
Please search next time, this is intended.

**Comment by phricardorj** [comment]
Lost in ignorance, but could you tell me why? Honestly, I didn't find about this question on the web. It would be of great help to my learning. Thank you very much in advance

**Comment by phricardorj** [comment]
Lost in ignorance, but could you tell me why? Honestly, I didn't find about this question on the web. It would be of great help to my learning. Thank you very much in advance

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/issues/535#issuecomment-1082644840

**Pull request closed without merging**
