### PR TITLE
Add back apply, bind, and call from Function

### LINKED ISSUE #388: Missing standard Function prototype (e.g. chalk.apply is not a function)
I was logging a lot of things to stderr in my TypeScript project, so I wanted to create a neat wrapper for this:

```ts
function log (text: TemplateStringsArray, ...placeholders: unknown[]): void {
  console.error(chalk.stderr(text, ...placeholders))
}
```

Unfortunately, this yielded the following error:

```text
TypeError: chalk.apply is not a function
    at log (/foo/bar.ts:2:22)
```

I hadn't yet setup a `tsconfig`, so my project was targeting ES5. This meant that the `...placeholders` call was converted to use `.apply`, which is assumed to exist on every function.

However, since chalk changes the prototype of the function, there is no longer any `apply`, `call` or other things from the `Function` prototype.

I think that this could be easily resolved by adding in `apply`, `call`, etc. manually. But I wanted to open this to get some feedback first.

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #388

### CODE REVIEW

**Comment by Qix-** [comment]
I'm not at a machine right now that I can test this; does this apply to e.g. `chalk.red` or only the root `chalk` object?

**Comment by ExE-Boss** [comment]
A better option might be to do:
```js
Object.setPrototypeOf(Chalk.prototype, Function.prototype);
```

**Comment by LinusU** [comment]
@ExE-Boss Hmm, actually, `Chalk` is already a function, so it should already have the function prototype, but then why isn't it working as it is? 🤔 

```
function Chalk () { ... }

const chalk = {}
chalk.template = (...arguments_) => chalkTag(chalk.template, ...arguments_)

Object.setPrototypeOf(chalk, Chalk.prototype)
Object.setPrototypeOf(chalk.template, chalk)
```

Shouldn't the prototype chain here be `chalk.template` -> `chalk` -> `Chalk.prototype` -> `Function.prototype`? Or am I missing something? 🤔

**Comment by ExE-Boss** [comment]
The prototype chain is: `chalk.template` → `chalk` → `Chalk.prototype` → `Object.prototype` → `null`.

**Comment by LinusU** [comment]
Screenshot 2020-04-03 at 14 01 02

Hmm, I just don't understand why `Chalk.prototype` is pointing to `Object.prototype` when it's just defined as a function in the code. I mean obviously I'm missing something 😁

**Comment by ExE-Boss** [comment]
That’s standard **ECMAScript** behaviour: <https://tc39.es/ecma262/#sec-makeconstructor>.

The `prototype` property of constructable functions is initialised to a plain object with its prototype set to `Object.prototype`.

This object is used [to create new instances by the `new` operator](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/new#Description) and [to check for inheritance by the `instanceof` operator](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/instanceof#Description).

**Comment by LinusU** [comment]
Ahh, of course 🤦‍♂

Thanks for pointing me in the right direction!

Yeah, doing `Object.setPrototypeOf(Chalk.prototype, Function.prototype)` is probably a better option, will update the PR 👍

**Comment by drumenbassik** [comment]
1

**Comment by Qix-** [comment]
Ping @LinusU

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by LinusU** [comment]
Sorry for the lack of response. I don't personally need this anymore since I don't use `apply` now that `...` is natively supported.

**Pull request closed without merging**
