### PR TITLE
Remove the blue color workaround for Windows

### LINKED ISSUE #329: Give some method to use original "blue" even under Windows
I saw this in `index.js`

```js
// Use bright blue on Windows as the normal blue color is illegible
if (isSimpleWindowsTerm) {
	ansiStyles.blue.open = '\u001B[94m';
}
```

But sometimes we may need to explicitly use the original `blue` even if it is not legible.

### PR DESCRIPTION
**Pull request by sindresorhus**
The illegible blue color has been fixed in Windows 10 build 16257: https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/

The workaround causes all kinds of problems, so better to remove it than adding conditionals for older Windows versions.

Fixes #329

### CODE REVIEW

**Comment by sindresorhus** [comment]
@be5invis Do you know if https://github.com/chalk/chalk/issues/58 has been fixed in Windows 10 yet? Would have been nice to be able to remove https://github.com/chalk/chalk/blob/60959e05cfe7086a38927eae5b5e04c459ce4182/index.js#L144-L145 too.

**Comment by be5invis** [comment]
@sindresorhus 
This is in RS5 (1809)
image
The workaround may be still needed for legacy versions (7, 8, etc.). Perhaps you can still enable it when `supports-color` returns 1.

**Comment by sindresorhus** [comment]
@be5invis #58 was using cmd.exe, not PowerShell.

**Comment by be5invis** [comment]
@sindresorhus 
image
I think this is more clear.
I do not have older builds currently (though there server have **all** the historical Windows builds).
You can remove these workarounds only for version >= 17763.

**Comment by Qix-** [comment]
Have they also fixed the dim issue entirely? If so then let's remove the simple windows term check entirely as @be5invis mentioned.

**Comment by sindresorhus** [comment]
> Have they also fixed the dim issue entirely? If so then let's remove the simple windows term check entirely as @be5invis mentioned.

Seems so from the comments above. I'll do that in a separate PR.

**Comment by sindresorhus** [comment]
> You can remove these workarounds only for version >= 17763.

Not interested in supporting older builds. This workaround complicates a lot of code. Users can easily upgrade to latest Windows builds.

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/pull/331

**Pull request merged**
